// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI-only URL. Prefer DIRECT_URL (unpooled) for migrations since
    // Neon's pooler rejects the long DDL transactions prisma migrate
    // needs. App runtime keeps reading DATABASE_URL from env directly.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
